const productDetail = [
  {
    id: 1,
    Title: "mobic paper wallet",
    cat: "paper wallet",
    Price: 100000,
    img: "./img/tp1.jpg",
  },
  {
    id: 2,
    Title: "mobic paper wallet",
    cat: "paper wallet",
    Price: 100000,
    img: "./img/tp2.jpg",
  },
  {
    id: 3,
    Title: "mobic paper wallet",
    cat: "paper wallet",
    Price: 100000,
    img: "./img/tp3.jpg",
  },
  {
    id: 4,
    Title: "mobic paper wallet",
    cat: "paper wallet",
    Price: 100000,
    img: "./img/tp4.jpg",
  },
  {
    id: 5,
    Title: "mobic paper wallet",
    cat: "paper wallet",
    Price: 100000,
    img: "./img/tp5.jpg",
  },
  {
    id: 6,
    Title: "mobic paper wallet",
    cat: "paper wallet by mobicus",
    Price: 100000,
    img: "./img/tp6.png",
  },
  {
    id: 7,
    Title: "mobic paper wallet",
    cat: "paper wallet by mobicus",
    Price: 100000,
    img: "./img/tp7.jpg",
  },
  {
    id: 8,
    Title: "mobic paper wallet",
    cat: "paper wallet by mobicus",
    Price: 100000,
    img: "./img/tp8.jpg",
  },
  {
    id: 9,
    Title: "mobic paper wallet",
    cat: "paper wallet by mobic",
    Price: 100000,
    img: "./img/p9.jpg",
  },
  {
    id: 10,
    Title: "mobic paper wallet",
    cat: "paper wallet by mobic",
    Price: 100000,
    img: "./img/p10.jpg",
  },
  {
    id: 11,
    Title: "mobic paper wallet",
    cat: "paper wallet by mobic",
    Price: 100000,
    img: "./img/p11.jpg",
  },
  {
    id: 12,
    Title: "mobic paper wallet",
    cat: "paper wallet by mobic",
    Price: 100000,
    img: "./img/p12.jpg",
  },
];

export default productDetail;
